'use strict';
const BUILD='2026.10.02-01';
const canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d',{alpha:false});
const $=s=>document.querySelector(s);let W=1280,H=720,dpr=1,state='ready',last=0,elapsed=0,distance=0,score=0,best=0,speed=310,jumpBuffer=0,coyote=0,steps=0,platforms=[],fish=[],particles=[],history=[],lastScore=-1;
try{best=Number(localStorage.getItem('iceRunBest'))||0}catch{}$('#best').textContent=best;
const images={};const load=(key,url)=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>{images[key]=i;resolve()};i.onerror=reject;i.src=url});
const cat={x:340,y:475,vy:0,ground:true,jumps:0};
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(window.devicePixelRatio||1,3);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);W=1280;H=720;ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
window.addEventListener('resize',resize);resize();
function clock(){const n=new Date();$('#clock').textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')}clock();setInterval(clock,1000);
function reset(){distance=elapsed=score=collected=0;speed=310;steps=0;jumpBuffer=coyote=0;fish=[];particles=[];history=[];platforms=[{x:-200,y:552,w:850}];Object.assign(cat,{x:340,y:552,vy:0,ground:true,jumps:0});for(let i=0;i<9;i++)extend();lastScore=-1}
function extend(){const p=platforms[platforms.length-1],gap=100+Math.random()*65,w=230+Math.random()*130,y=Math.max(500,Math.min(582,p.y+(Math.random()-.5)*60));const n={x:p.x+p.w+gap,y,w};platforms.push(n);fish.push({x:n.x+n.w*.52,y:y-130,taken:false})}
function jump(){if(state!=='running')return;jumpBuffer=.13;if(cat.ground||coyote>0||cat.jumps<2){cat.vy=-660;cat.ground=false;cat.jumps++;jumpBuffer=0;coyote=0;burst(cat.x-35,cat.y,7)}}
function burst(x,y,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*150,vy:-60-Math.random()*150,t:.5})}
function pause(){if(state==='running'){state='paused';$('#panel').classList.remove('hidden');$('#message').textContent='一時停止中';$('#start').textContent='つづける ▷';$('#pause').textContent='▷'}else if(state==='paused'){state='running';$('#panel').classList.add('hidden');$('#pause').textContent='Ⅱ'}}
$('#pause').onclick=pause;$('#start').onclick=()=>{if(state==='loading')return;if(state==='paused'){pause();return}reset();state='running';$('#panel').classList.add('hidden');$('#pause').textContent='Ⅱ'};
$('#jump').addEventListener('pointerdown',e=>{e.preventDefault();jump()});canvas.addEventListener('pointerdown',e=>{e.preventDefault();jump()});window.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();if(!e.repeat)jump()}if(e.code==='Escape')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause()});
function end(){state='over';best=Math.max(best,score);try{localStorage.setItem('iceRunBest',best)}catch{}$('#best').textContent=best;$('#message').textContent='今回のスコア '+score+' · ベスト '+best;$('#start').textContent='もう一度 ▷';$('#panel').classList.remove('hidden')}
function update(dt){elapsed+=dt;distance+=speed*dt;speed=Math.min(455,310+elapsed*1.4);jumpBuffer-=dt;coyote-=dt;const old=cat.y;cat.vy+=1800*dt;cat.y+=cat.vy*dt;cat.ground=false;for(const p of platforms)p.x-=speed*dt;for(const p of platforms){if(cat.x+36>p.x&&cat.x-30<p.x+p.w&&old<=p.y+5&&cat.y>=p.y&&cat.vy>=0){cat.y=p.y;cat.vy=0;cat.ground=true;cat.jumps=0;coyote=.1;if(jumpBuffer>0)jump();break}}if(cat.ground&&Math.floor(elapsed*12)>steps){steps=Math.floor(elapsed*12);burst(cat.x-45,cat.y,2)}while(platforms[0].x+platforms[0].w<-150)platforms.shift();while(platforms[platforms.length-1].x<1700)extend();for(const f of fish){f.x-=speed*dt;if(!f.taken&&Math.abs(f.x-cat.x)<72&&Math.abs(f.y-(cat.y-55))<74){f.taken=true;collected+=50;burst(f.x,f.y,14)}}fish=fish.filter(f=>f.x>-160&&!f.taken);score=Math.floor(distance/25)+collected;history.push({t:elapsed,y:cat.y,vy:cat.vy,ground:cat.ground});while(history.length>2&&history[1].t<elapsed-.32)history.shift();for(const p of particles){p.t-=dt;p.x+=p.vx*dt-speed*dt*.4;p.y+=p.vy*dt;p.vy+=400*dt}particles=particles.filter(p=>p.t>0);if(cat.y>H+100)end()}
let collected=0;
function sprite(col,row,x,y,w,h,angle=0){const a=images.atlas,sw=a.width/4,sh=a.height/3;let sy=row*sh+90,hh=sh-90;if(row===2&&col===2){sy=row*sh+115;hh=175}if(row===2&&col===3){sy=row*sh+75;hh=230}ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.drawImage(a,col*sw,sy,sw,hh,-w/2,-h,w,h);ctx.restore()}
function draw(){ctx.drawImage(images.bg,0,0,W,H);const drift=(distance*.15)%W;ctx.globalAlpha=.12;ctx.drawImage(images.bg,-drift,0,W,H);ctx.drawImage(images.bg,W-drift,0,W,H);ctx.globalAlpha=1;for(const p of platforms){sprite(2,2,p.x+p.w/2,p.y+110,p.w+24,110)}for(const f of fish){sprite(3,2,f.x,f.y+34+Math.sin(elapsed*3+f.x)*8,128,92)}const frame=Math.floor(elapsed*11)%4,follow=history[0]||cat;const followerY=state==='ready'?552:follow.y;const followerJump=!follow.ground; sprite(followerJump?1:frame,followerJump?2:1,cat.x-140,followerY+4,184,145,followerJump?(follow.vy>100?.12:-.08):0);sprite(cat.ground?frame:0,cat.ground?0:2,cat.x,cat.y+4,208,160,cat.ground?0:(cat.vy>100?.16:-.09));for(const p of particles){ctx.globalAlpha=Math.min(1,p.t*2);ctx.fillStyle='#d3faff';ctx.fillRect(p.x,p.y,4,4)}ctx.globalAlpha=1;if(score!==lastScore){$('#score').textContent=score;lastScore=score}}
function loop(now){const dt=Math.min((now-last)/1000||0,.034);last=now;if(images.bg&&images.atlas){if(state==='running')update(dt);draw()}requestAnimationFrame(loop)}
state='loading';Promise.all([load('bg','assets/background.webp'),load('atlas','assets/sprites.png')]).then(()=>{reset();state='ready';$('#loading').classList.add('hidden');requestAnimationFrame(loop)}).catch(()=>{$('#loading').textContent='画像を読み込めません。assetsフォルダも一緒に配置してください。'});
window.iceRun={get state(){return state},get cat(){return {...cat}},get score(){return score},build:BUILD};
